---
version: '3'
services:
  web:
    build: .
    ports:
     - "8080:4000"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run watch:css & jekyll serve --host 0.0.0.0 --incremental --limit_posts 15 --future --drafts"
